WAKE_WORDS = ("mai", "jarvis")
IDLE_TIMEOUT = 5 * 60  # seconds; switches to sleep mode after this many seconds without a successful command

VOCABULARY_LIST = [
    "mai", "jarvis",
    "exit", "stop",
    "hello", "hi", "how are you",
    "switch",
    "pause", "play", "resume", "continue",
    "next", "previous", "prev", "back",
    "track", "song", "music",
    "open", "launch", "run", "close", "tab", "new", "reopen", "to",
    "next tab", "previous tab", "new tab", "close tab", "reopen tab", "switch tab",
    "minimize", "maximize", "fullscreen", "full screen", "restore", "show", "desktop", "window", "all",
    "minimize window", "maximize window", "minimize all", "restore all", "show desktop",
    "terminate", "kill", "shut down", "shutdown",
    "volume", "louder", "quieter", "up", "down", "mute",
    "volume up", "volume down",
    "spotify", "chrome", "google", "vs code", "code", "visual studio code", "visual studio",
    "telegram", "tg", "discord", "notepad", "hap", "happ", "firefox", "zen", "browser",
    "steam", "explorer", "file", "file explorer", "task manager", "obsidian",
    "lightroom", "adobe lightroom classic", "exit lag",
    "intellij", "idea", "intellij idea", "nvidia", "app", "nvidia app"
]

APP_ALIASES = {
    "spotify": "spotify.exe",
    "chrome": "chrome.exe",
    "google": "chrome.exe",
    "vs code": "Code.exe",
    "code": "Code.exe",
    "visual studio code": "Code.exe",
    "telegram": "Telegram.exe",
    "tg": "Telegram.exe",
    "discord": "Discord.exe",
    "notepad": "Notepad.exe",
    "hap": "Happ.exe",
    "happ": "Happ.exe",
    "firefox": "firefox.exe",
    "browser": "zen.exe",
    "zen": "zen.exe",
    "steam": "steamwebhelper.exe",
    "explorer": "explorer.exe",
    "task manager": "taskmgr.exe",
    "obsidian": "obsidian.exe",
    # Names taken from the real taskbar pin shortcuts
    "visual studio": "devenv.exe",
    "lightroom": "Lightroom.exe",
    "adobe lightroom classic": "Lightroom.exe",
    "intellij": "idea64.exe",
    "idea": "idea64.exe",
    "intellij idea": "idea64.exe",
    "nvidia": "NVIDIA App.exe",
    "nvidia app": "NVIDIA App.exe",
    "exit lag": "ExitLag.exe",
}
